### ISSUE TITLE
QuickSel compilation issues

### ISSUE THREAD

**Issue by ggonzalezaraujo** [sfu-db/quicksel#1]
I am having issues running QuickSel on macOS Big Sur. I have installed Java and Apache Maven using brew. When I run, I receive the following error:

```mvn compile assembly:single
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------------< quickSel:quickSel >--------------------------
[INFO] Building QuickSel: Quick Selectivity Learning 0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ quickSel ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/giovanni_gonzalez/Desktop/Big Data Science/Labs/AreCELearnedYet/lecarb/estimator/quicksel/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ quickSel ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 24 source files to /Users/giovanni_gonzalez/Desktop/Big Data Science/Labs/AreCELearnedYet/lecarb/estimator/quicksel/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.294 s
[INFO] Finished at: 2021-04-13T16:01:09-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project quickSel: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
make: *** [all] Error 1```

**Comment by dovahcrow** [comment]
It looks like the java compiler is not installed correctly. Could you confirm that the JDK is installed instead of JRE and `javac` is in your `PATH`?

**Comment by ggonzalezaraujo** [comment]
How can I verify that I have installed the JDK instead of JRE?

**Comment by dovahcrow** [comment]
Maybe you can follow this question: https://stackoverflow.com/questions/22539779/how-to-tell-if-jre-or-jdk-is-installed

**Comment by ggonzalezaraujo** [comment]
I did have JRE instead of JDK. Thank you for the help!

I have successfully executed `make all`, but now when I try to run the rest of the examples, I run into some more errors.

```make exp_scan
java -Dproject_home=/Users/giovanni_gonzalez/Desktop/Big Data Science/Labs/AreCELearnedYet/lecarb/estimator/quicksel \
        -classpath target/test-classes:target/quickSel-0.1-jar-with-dependencies.jar \
    -Xmx32g -Xms1g edu.illinois.quicksel.experiments.PerAttAndSamplingTest
Error: Could not find or load main class Data
Caused by: java.lang.ClassNotFoundException: Data
make: *** [exp_scan] Error 1```

**Comment by dovahcrow** [comment]
Please escape the spaces in your path or move the project to a folder with no spaces in its path. `Big Data Science`

**Comment by ggonzalezaraujo** [comment]
I changed the name of the folder. Now, it seems that the file dmv data file is not found. 

```
java -Dproject_home=/Users/giovanni_gonzalez/Desktop/Big_Data_Science/Labs/AreCELearnedYet/lecarb/estimator/quicksel \
        -classpath target/test-classes:target/quickSel-0.1-jar-with-dependencies.jar \
        -Xmx32g -Xms1g edu.illinois.quicksel.experiments.DMVSpeedComparison
Assertion File: DMV/assertion_dmv.txt
Exception in thread "main" java.io.FileNotFoundException: ../data/DMV/assertion_dmv.txt (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:108)
        at java.base/java.io.FileReader.<init>(FileReader.java:60)
        at edu.illinois.quicksel.basic.AssertionReader.readAssertion(AssertionReader.java:133)
        at edu.illinois.quicksel.experiments.DMVSpeedComparison.main(DMVSpeedComparison.java:18)
make: *** [exp_dmv] Error 1
```

**Comment by ggonzalezaraujo** [comment]
I have downloaded the data set from `https://www.dropbox.com/s/5bmvc1si5hysapf/data.tar.gz?dl=0`, but it does not have the `assertion_dmv.txt`.
